// Archivo generado automáticamente por Ricardo AI System. NO EDITAR DIRECTAMENTE.
const ROUTER_NEWS_DATA = [
  {
    "id": 119,
    "date": "2026-06-12",
    "title": "⚡ Cámaras Autónomas: Seguridad Solar en Sectores Rurales",
    "desc": "Aura analiza cómo los kits de CCTV solar están revolucionando la seguridad de parcelas y sectores rurales sin conectividad eléctrica en la provincia de Arauco.",
    "image": "https://images.unsplash.com/photo-1508514177221-188b1cf16e9d?w=600&auto=format&fit=crop&q=80",
    "content": "\n                    <p>La seguridad en predios agrícolas, parcelas de agrado e instalaciones forestales en la provincia de Arauco ha enfrentado históricamente un gran obstáculo: la falta de empalme eléctrico y conectividad de red por cable.</p>\n                    <h4>CCTV Solar: Independencia Energética</h4>\n                    <p>La solución que se está consolidando en comunas como Cañete, Lebu y Contulmo son los sistemas de CCTV autónomos alimentados por paneles solares fotovoltaicos y baterías de litio de descarga profunda. Estos sistemas captan la radiación del día y almacenan energía suficiente para alimentar cámaras PTZ (domo robótico) de bajo consumo durante la noche y días nublados.</p>\n                    <h4>Monitoreo 4G y Almacenamiento Local</h4>\n                    <p>Al no contar con internet físico, estas cámaras utilizan enlaces móviles de alta velocidad 4G/LTE con chips dedicados. De esta forma, el propietario puede recibir notificaciones instantáneas de detección de movimiento, mover la cámara 360° desde su celular y revisar grabaciones almacenadas localmente en tarjetas MicroSD de nivel industrial o en pequeños NVR autónomos de bajo voltaje.</p>\n                    <h4>Cero Cuotas y Control Total</h4>\n                    <p>Frente a las costosas alternativas de grandes corporaciones que exigen mensualidades por un servicio que no cubre zonas rurales, el modelo de Router consiste en la venta e instalación directa del kit solar, traspasando la propiedad absoluta del equipamiento al cliente, sin cobros de arriendo recurrentes.</p>\n                "
  },
  {
    "id": 118,
    "date": "2026-06-12",
    "title": "🛰️ Conectividad Satelital: Starlink e Inteligencia de Vigilancia",
    "desc": "La integración de Starlink con cámaras Hikvision AcuSense permite vigilar escuelas rurales y juntas de vecinos aisladas en tiempo real en todo el Biobío.",
    "image": "https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=600&auto=format&fit=crop&q=80",
    "content": "\n                    <p>La conectividad satelital de Starlink está transformando la viabilidad técnica de los proyectos de seguridad en zonas rurales del Biobío. Juntas de vecinos y escuelas aisladas que antes no tenían factibilidad de internet, hoy pueden integrarse a redes de vigilancia en alta definición.</p>\n                    <h4>Starlink: Banda Ancha en Zonas Aisladas</h4>\n                    <p>Gracias a la constelación de satélites de órbita baja de SpaceX, es posible obtener latencias inferiores a 40ms y velocidades de subida de hasta 20 Mbps en cualquier rincón de la provincia de Arauco. Esta capacidad permite el streaming fluido de múltiples canales de video en alta definición (1080p y 4K) sin microcortes.</p>\n                    <h4>Vigilancia Comunitaria Centralizada</h4>\n                    <p>Al integrar Starlink con grabadores NVR Hikvision y la app Hik-Connect, los comités de seguridad pueden compartir el acceso a las cámaras de la sede vecinal o la escuela local. Ante cualquier evento sospechoso, los vecinos reciben una alerta con video en tiempo real, permitiendo una coordinación comunitaria inmediata y efectiva con Carabineros.</p>\n                    <h4>Proyectos FNDR y Subsidios Estatales</h4>\n                    <p>El uso de estas tecnologías mixtas (Starlink + CCTV) ha demostrado ser el factor clave para la aprobación de fondos gubernamentales (FNDR) de seguridad pública. Los evaluadores técnicos priorizan proyectos que demuestran una factibilidad de conectividad real e independiente de la infraestructura telefónica local.</p>\n                "
  },
  {
    "id": 117,
    "date": "2026-06-12",
    "title": "🧠 Detección Inteligente: Menos Alarmas Falsas en CCTV con IA",
    "desc": "Aura detalla cómo los algoritmos de detección humana y vehicular de Hikvision AcuSense optimizan el monitoreo comercial y evitan falsos positivos.",
    "image": "https://images.unsplash.com/photo-1557597774-9d273605dfa9?w=600&auto=format&fit=crop&q=80",
    "content": "\n                    <p>El monitoreo tradicional de cámaras de seguridad se ve constantemente plagado por alertas innecesarias causadas por hojas que se mueven, mascotas, lluvia o sombras. La Inteligencia Artificial aplicada a CCTV ha llegado para resolver este problema crónico.</p>\n                    <h4>Tecnología AcuSense de Hikvision</h4>\n                    <p>Los algoritmos de aprendizaje profundo (Deep Learning) integrados en las cámaras y grabadores Hikvision AcuSense clasifican instantáneamente los objetos que aparecen en pantalla en tres categorías: humanos, vehículos y otros. De esta manera, el sistema ignora el movimiento de ramas o animales y solo activa la alarma cuando una persona o un automóvil cruzan una línea virtual establecida.</p>\n                    <h4>Monitoreo Eficiente y Notificaciones en Celular</h4>\n                    <p>Para el propietario de un negocio o vivienda en Arauco, esto significa que las notificaciones push que llegan a su celular son 90% reales. Ya no es necesario revisar el teléfono a mitad de la noche por un perro que pasó frente a la cámara; el sistema solo alertará ante riesgos auténticos de intrusión.</p>\n                    <h4>Búsqueda Rápida de Evidencia</h4>\n                    <p>Al momento de revisar grabaciones tras un incidente, la IA permite filtrar las últimas 24 horas buscando exclusivamente \"aparición de vehículos\" o \"aparición de personas\". Lo que antes tomaba horas de revisión manual de grabaciones ahora se resuelve en menos de un minuto.</p>\n                "
  }
];
